import { MenuItem } from "./types";

export const INITIAL_ITEMS: MenuItem[] = [
  // --- Bebidas ---
  { id: '100', name: 'Água', selected: true },
  { id: '101', name: 'Água com Gás', selected: true },
  { id: '102', name: 'Água Saborizada', selected: false },
  { id: '103', name: 'Café', selected: true },
  { id: '104', name: 'Leite', selected: false },
  { id: '105', name: 'Chá', selected: false },
  { id: '106', name: 'Suco de Maracujá', selected: false },
  { id: '107', name: 'Suco de Uva', selected: false },
  { id: '108', name: 'Suco de Caju', selected: false },
  { id: '109', name: 'Suco de Laranja', selected: false },
  { id: '110', name: 'Suco de Goiaba', selected: false },
  { id: '111', name: 'Suco de Abacaxi com Hortelã', selected: false },
  { id: '112', name: 'Suco de Manga', selected: false },
  { id: '113', name: 'Suco de Morango', selected: false },
  { id: '114', name: 'Refrigerante', selected: false },
  { id: '115', name: 'Refrigerante Zero', selected: false },
  { id: '116', name: 'Matte', selected: false },

  // --- Sanduíches e Pães ---
  { id: '200', name: 'Sanduíche de Pão de Forma Salpicão', selected: false },
  { id: '201', name: 'Mini Sanduíche de Pasta de Alho Poró', selected: true },
  { id: '202', name: 'Mini Sanduíche de Pasta de Frango', selected: false },
  { id: '203', name: 'Sanduíche de Pasta de Frango com Milho', selected: false },
  { id: '204', name: 'Sanduíche de Pasta de Frango e Alface', selected: false },
  { id: '205', name: 'Mini Sanduíche de Bacon com Cream Cheese', selected: false },
  { id: '206', name: 'Sanduíche de Pasta de Bacon', selected: false },
  { id: '207', name: 'Mini Sanduíche de Lombo com Cheddar', selected: false },
  { id: '208', name: 'Mini Sanduíche de Homus Tahine', selected: false },
  { id: '209', name: 'Mini Sanduíche de Peito de Peru com Cream Cheese', selected: false },
  { id: '210', name: 'Mini Sanduíche de Salame com Requeijão', selected: false },
  { id: '211', name: 'Mini Sanduíche Bicolor', selected: false },
  { id: '212', name: 'Sanduíche a Metro com Pasta de Alho Poró', selected: false },
  { id: '213', name: 'Mini Ciabatta de Salpicão', selected: false },
  { id: '214', name: 'Mini Pão Francês com Peito de Peru', selected: false },
  { id: '215', name: 'Mini Pão Francês com Salpicão', selected: false },
  { id: '216', name: 'Mini Pão Francês com Presunto e Cream Cheese', selected: false },
  { id: '217', name: 'Croissant de Frango', selected: false },
  { id: '218', name: 'Croissant de Queijo e Presunto', selected: false },
  { id: '219', name: 'Croissant de Queijo', selected: false },
  { id: '220', name: 'Pão de Queijo', selected: true },
  { id: '221', name: 'Pão de Alho', selected: false },
  { id: '222', name: 'Torradas', selected: false },
  { id: '223', name: 'Pães e Pastas', selected: false },

  // --- Salgados Quentes ---
  { id: '300', name: 'Coxinha da Asa', selected: false },
  { id: '301', name: 'Coxinha', selected: false },
  { id: '302', name: 'Quiche Lorraine', selected: true },
  { id: '303', name: 'Quiche de Cebola', selected: false },
  { id: '304', name: 'Quiche de Alho Poró', selected: true },
  { id: '305', name: 'Quiche de Queijo', selected: false },
  { id: '306', name: 'Quiche de Provolone', selected: false },
  { id: '307', name: 'Quiche Seco', selected: false },
  { id: '308', name: 'Quiche de Frango', selected: false },
  { id: '309', name: 'Empada de Palmito', selected: false },
  { id: '310', name: 'Mini Empada de Camarão', selected: false },
  { id: '311', name: 'Pastel de Forno de Frango', selected: false },
  { id: '312', name: 'Pastel de Forno de Carne', selected: false },
  { id: '313', name: 'Mini Pastel de Forno de Queijo', selected: false },
  { id: '314', name: 'Esfiha de Carne', selected: false },
  { id: '315', name: 'Mini Esfiha de Carne', selected: false },
  { id: '316', name: 'Folhado de Frango', selected: false },
  { id: '317', name: 'Mini Folhado de Bacalhau', selected: false },
  { id: '318', name: 'Enroladinho de Escarola', selected: false },
  { id: '319', name: 'Trouxinha de Palmito', selected: false },
  { id: '320', name: 'Trouxinha de Queijo', selected: false },
  { id: '321', name: 'Bolinha de Queijo', selected: false },
  { id: '322', name: 'Mini Salgados tipo Bolinho de Bacalhau', selected: false },
  { id: '323', name: 'Mini Salgados tipo Quibe', selected: false },
  { id: '324', name: 'Queijo Coalho', selected: false },
  { id: '325', name: 'Coração de Frango', selected: false },
  { id: '326', name: 'Linguiça de Pernil e Frango', selected: false },
  { id: '327', name: 'Alcatra', selected: false },
  { id: '328', name: 'Maminha', selected: false },

  // --- Pratos Quentes / Refeições ---
  { id: '400', name: 'Arroz à Piamontese', selected: false },
  { id: '401', name: 'Arroz Branco', selected: false },
  { id: '402', name: 'Risoto de Camarão com Alho Poró', selected: false },
  { id: '403', name: 'Penne ao Molho Pomodoro com Manjericão', selected: false },
  { id: '404', name: 'Ragu de Carne ao Molho Madeira', selected: false },
  { id: '405', name: 'Iscas de Frango com Batata Doce', selected: false },
  { id: '406', name: 'Escondidinho de Carne Seca', selected: false },
  { id: '407', name: 'Creme Quente de Bacalhau', selected: false },
  { id: '408', name: 'Bobó de Camarão na Mini Moranga', selected: false },
  { id: '409', name: 'Batata Souté', selected: false },
  { id: '410', name: 'Batata Rústica', selected: false },

  // --- Saladas e Frios ---
  { id: '500', name: 'Salada de Frutas', selected: false },
  { id: '501', name: 'Salada de Frutas com Iogurte e Granola', selected: false },
  { id: '502', name: 'Salada Tropical', selected: false },
  { id: '503', name: 'Salada Waldorf', selected: false },
  { id: '504', name: 'Carpaccio de Carne com Parmesão', selected: false },
  { id: '505', name: 'Tábua de Frios', selected: true },
  { id: '506', name: 'Espeto de Frutas', selected: false },
  { id: '507', name: 'Banana', selected: false },

  // --- Bolos e Doces ---
  { id: '600', name: 'Bolo de Laranja', selected: false },
  { id: '601', name: 'Bolo de Limão Siciliano', selected: false },
  { id: '602', name: 'Bolo Red Velvet', selected: false },
  { id: '603', name: 'Bolo de Fubá com Goiabada', selected: false },
  { id: '604', name: 'Bolo de Banana com Canela', selected: false },
  { id: '605', name: 'Bolo de Coco', selected: false },
  { id: '606', name: 'Bolo de Chocolate', selected: false },
  { id: '607', name: 'Bolo de Baunilha', selected: false },
  { id: '608', name: 'Bolo de Maçã', selected: false },
  { id: '609', name: 'Bolo de Maçã com Nozes', selected: false },
  { id: '610', name: 'Bolo de Milho Cremoso', selected: false },
  { id: '611', name: 'Bolo de Iogurte com Ninho', selected: false },
  { id: '612', name: 'Bolo Formigueiro', selected: false },
  { id: '613', name: 'Bolo de Aipim', selected: false },
  { id: '614', name: 'Torta de Limão', selected: false },
  { id: '615', name: 'Torta de Queijo', selected: false },
  { id: '616', name: 'Tortinha de Maracujá', selected: false },
  { id: '617', name: 'Petit Four', selected: false },
  { id: '618', name: 'Biscoitos', selected: false },
  { id: '619', name: 'Biscoitos Finos', selected: false },
  { id: '620', name: 'Balas Variadas', selected: false },
  { id: '621', name: 'Gotinhas de Chocolate', selected: false },
  { id: '622', name: 'Bombinha de Chocolate', selected: false },
  { id: '623', name: 'Carolina Recheada', selected: false },
  { id: '624', name: 'Sonhos de Creme', selected: false },
  { id: '625', name: 'Sonhos de Doce de Leite', selected: false },
  { id: '626', name: 'Rosquinha de Chocolate', selected: false },
  { id: '627', name: 'Rosquinha de Doce de Leite', selected: false },
  { id: '628', name: 'Cocada com Chocolate', selected: false },
  { id: '629', name: 'Tartelete de Damasco e Brie', selected: false },
  { id: '630', name: 'Tirinhas de Laranja', selected: false },
];

// This is the approximate "Sebrae Blue" or the pen ink blue from the image
export const THEME_COLOR = '#005CA9';